use chrono::NaiveDateTime;
use sea_orm::prelude::Decimal;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Serialize, Deserialize, Default)]
pub struct PairRequest {
    pub id: Option<i32>,
    pub base_asset_id: Option<i32>,
    pub quote_asset_id: Option<i32>,
    pub symbol: Option<String>,
    pub update_date: Option<NaiveDateTime>,
    pub last_price: Option<Decimal>,
    pub all_time_high_price: Option<Decimal>,
    pub all_time_high_date: Option<NaiveDateTime>,
    pub percent_from_all_time_high: Option<Decimal>,
    pub fifteen_minutes_price_percent_change: Option<Decimal>,
    pub thirty_minutes_price_percent_change: Option<Decimal>,
    pub hour_price_percent_change: Option<Decimal>,
    pub six_hours_price_percent_change: Option<Decimal>,
    pub twelve_hours_price_percent_change: Option<Decimal>,
    pub day_price_percent_change: Option<Decimal>,
    pub week_price_percent_change: Option<Decimal>,
    pub month_price_percent_change: Option<Decimal>,
    pub year_price_percent_change: Option<Decimal>,
    pub price_filter_min_price: Option<Decimal>,
    pub price_filter_max_price: Option<Decimal>,
    pub price_filter_tick_size: Option<Decimal>,
    pub lot_size_min_qty: Option<Decimal>,
    pub lot_size_max_qty: Option<Decimal>,
    pub lot_size_step_size: Option<Decimal>,
    pub iceberg_parts_limit: Option<i32>,
    pub market_lot_size_min_qty: Option<Decimal>,
    pub market_lot_size_max_qty: Option<Decimal>,
    pub market_lot_size_step_size: Option<Decimal>,
    pub trailing_delta_min_trailing_above_delta: Option<i32>,
    pub trailing_delta_max_trailing_above_delta: Option<i32>,
    pub trailing_delta_min_trailing_below_delta: Option<i32>,
    pub trailing_delta_max_trailing_below_delta: Option<i32>,
    pub percent_price_by_side_bid_multiplier_up: Option<Decimal>,
    pub percent_price_by_side_bid_multiplier_down: Option<Decimal>,
    pub percent_price_by_side_ask_multiplier_up: Option<Decimal>,
    pub percent_price_by_side_ask_multiplier_down: Option<Decimal>,
    pub percent_price_by_side_avg_price_mins: Option<i32>,
    pub notional_min_notional: Option<Decimal>,
    pub notional_apply_min_to_market: Option<bool>,
    pub notional_max_notional: Option<Decimal>,
    pub notional_apply_max_to_market: Option<bool>,
    pub notional_avg_price_mins: Option<i32>,
    pub max_num_orders: Option<i32>,
    pub max_num_algo_orders: Option<i32>,
}
