//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "actions"
    }
}

#[derive(
    Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize, Default,
)]
pub struct Model {
    pub id: i32,
    pub strategy_id: i32,
    pub is_active: bool,
    pub is_sell: bool,
    pub is_quote_asset: bool,
    pub is_percentage: bool,
    pub value: Decimal,
    pub pair_id: i32,
    pub last_update: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    StrategyId,
    IsActive,
    IsSell,
    IsQuoteAsset,
    IsPercentage,
    Value,
    PairId,
    LastUpdate,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Pairs,
    Strategies,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::StrategyId => ColumnType::Integer.def(),
            Self::IsActive => ColumnType::Boolean.def(),
            Self::IsSell => ColumnType::Boolean.def(),
            Self::IsQuoteAsset => ColumnType::Boolean.def(),
            Self::IsPercentage => ColumnType::Boolean.def(),
            Self::Value => ColumnType::Decimal(Some((18u32, 8u32))).def(),
            Self::PairId => ColumnType::Integer.def(),
            Self::LastUpdate => ColumnType::DateTime.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Pairs => Entity::belongs_to(super::pairs::Entity)
                .from(Column::PairId)
                .to(super::pairs::Column::Id)
                .into(),
            Self::Strategies => Entity::belongs_to(super::strategies::Entity)
                .from(Column::StrategyId)
                .to(super::strategies::Column::Id)
                .into(),
        }
    }
}

impl Related<super::pairs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Pairs.def()
    }
}

impl Related<super::strategies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Strategies.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
