//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "assets"
    }
}

#[derive(
    Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize, Default,
)]
pub struct Model {
    pub id: i32,
    pub name: String,
    pub ticker: String,
    pub free: Decimal,
    pub locked: Decimal,
    pub last_update: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Name,
    Ticker,
    Free,
    Locked,
    LastUpdate,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Ledgers,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::Name => ColumnType::Text.def(),
            Self::Ticker => ColumnType::Text.def(),
            Self::Free => ColumnType::Decimal(Some((18u32, 8u32))).def(),
            Self::Locked => ColumnType::Decimal(Some((18u32, 8u32))).def(),
            Self::LastUpdate => ColumnType::DateTime.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Ledgers => Entity::has_many(super::ledgers::Entity).into(),
        }
    }
}

impl Related<super::ledgers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Ledgers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
