//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "critical_metrics"
    }
}

#[derive(
    Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize, Default,
)]
pub struct Model {
    pub id: i32,
    pub creation_date: DateTime,
    pub executions_ok: i64,
    pub executions_err: i64,
    pub total_execution_time: i64,
    pub max_execution_time: i64,
    pub slowest_duration: i64,
    pub active_posting: i64,
    pub max_active_posting: i64,
    pub skipped_due_to_lock: i64,
    pub last_success: Option<DateTime>,
    pub last_error: Option<DateTime>,
    pub consecutive_errors: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    CreationDate,
    ExecutionsOk,
    ExecutionsErr,
    TotalExecutionTime,
    MaxExecutionTime,
    SlowestDuration,
    ActivePosting,
    MaxActivePosting,
    SkippedDueToLock,
    LastSuccess,
    LastError,
    ConsecutiveErrors,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::CreationDate => ColumnType::DateTime.def(),
            Self::ExecutionsOk => ColumnType::BigInteger.def(),
            Self::ExecutionsErr => ColumnType::BigInteger.def(),
            Self::TotalExecutionTime => ColumnType::BigInteger.def(),
            Self::MaxExecutionTime => ColumnType::BigInteger.def(),
            Self::SlowestDuration => ColumnType::BigInteger.def(),
            Self::ActivePosting => ColumnType::BigInteger.def(),
            Self::MaxActivePosting => ColumnType::BigInteger.def(),
            Self::SkippedDueToLock => ColumnType::BigInteger.def(),
            Self::LastSuccess => ColumnType::DateTime.def().null(),
            Self::LastError => ColumnType::DateTime.def().null(),
            Self::ConsecutiveErrors => ColumnType::BigInteger.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
