//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "integrations"
    }
}

#[derive(
    Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize, Default,
)]
pub struct Model {
    pub id: i32,
    pub name: String,
    pub code: String,
    pub is_enabled: bool,
    pub creation_date: DateTime,
    pub last_update_date: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Name,
    Code,
    IsEnabled,
    CreationDate,
    LastUpdateDate,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    IntegrationSettings,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::Name => ColumnType::String(StringLen::None).def(),
            Self::Code => ColumnType::String(StringLen::None).def(),
            Self::IsEnabled => ColumnType::Boolean.def(),
            Self::CreationDate => ColumnType::DateTime.def(),
            Self::LastUpdateDate => ColumnType::DateTime.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::IntegrationSettings => {
                Entity::has_many(super::integration_settings::Entity).into()
            }
        }
    }
}

impl Related<super::integration_settings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IntegrationSettings.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
