//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "integration_settings"
    }
}

#[derive(
    Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize, Default,
)]
pub struct Model {
    pub id: i32,
    pub integration_id: i32,
    pub name: String,
    pub nick: String,
    pub value: String,
    pub creation_date: DateTime,
    pub last_update_date: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    IntegrationId,
    Name,
    Nick,
    Value,
    CreationDate,
    LastUpdateDate,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Integrations,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::IntegrationId => ColumnType::Integer.def(),
            Self::Name => ColumnType::String(StringLen::None).def(),
            Self::Nick => ColumnType::String(StringLen::None).def(),
            Self::Value => ColumnType::String(StringLen::None).def(),
            Self::CreationDate => ColumnType::DateTime.def(),
            Self::LastUpdateDate => ColumnType::DateTime.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Integrations => Entity::belongs_to(super::integrations::Entity)
                .from(Column::IntegrationId)
                .to(super::integrations::Column::Id)
                .into(),
        }
    }
}

impl Related<super::integrations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Integrations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
