//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "orders"
    }
}

#[derive(
    Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize, Default,
)]
pub struct Model {
    pub id: i32,
    pub status_id: i32,
    pub creation_date: DateTime,
    pub update_date: DateTime,
    pub is_sell: bool,
    pub strategy_id: i32,
    pub base_asset_id: i32,
    pub base_asset_amount: Decimal,
    pub quote_asset_id: i32,
    pub quote_asset_amount: Decimal,
    pub price_entry: Decimal,
    pub price_target: Decimal,
    pub price_abort: Decimal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    StatusId,
    CreationDate,
    UpdateDate,
    IsSell,
    StrategyId,
    BaseAssetId,
    BaseAssetAmount,
    QuoteAssetId,
    QuoteAssetAmount,
    PriceEntry,
    PriceTarget,
    PriceAbort,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Assets2,
    Assets1,
    Status,
    Strategies,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::StatusId => ColumnType::Integer.def(),
            Self::CreationDate => ColumnType::DateTime.def(),
            Self::UpdateDate => ColumnType::DateTime.def(),
            Self::IsSell => ColumnType::Boolean.def(),
            Self::StrategyId => ColumnType::Integer.def(),
            Self::BaseAssetId => ColumnType::Integer.def(),
            Self::BaseAssetAmount => ColumnType::Decimal(Some((18u32, 8u32))).def(),
            Self::QuoteAssetId => ColumnType::Integer.def(),
            Self::QuoteAssetAmount => ColumnType::Decimal(Some((18u32, 8u32))).def(),
            Self::PriceEntry => ColumnType::Decimal(Some((18u32, 8u32))).def(),
            Self::PriceTarget => ColumnType::Decimal(Some((18u32, 8u32))).def(),
            Self::PriceAbort => ColumnType::Decimal(Some((18u32, 8u32))).def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Assets2 => Entity::belongs_to(super::assets::Entity)
                .from(Column::BaseAssetId)
                .to(super::assets::Column::Id)
                .into(),
            Self::Assets1 => Entity::belongs_to(super::assets::Entity)
                .from(Column::QuoteAssetId)
                .to(super::assets::Column::Id)
                .into(),
            Self::Status => Entity::belongs_to(super::status::Entity)
                .from(Column::StatusId)
                .to(super::status::Column::Id)
                .into(),
            Self::Strategies => Entity::belongs_to(super::strategies::Entity)
                .from(Column::StrategyId)
                .to(super::strategies::Column::Id)
                .into(),
        }
    }
}

impl Related<super::status::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Status.def()
    }
}

impl Related<super::strategies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Strategies.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
