//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "error_log"
    }
}

#[derive(
    Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize, Default,
)]
pub struct Model {
    pub id: i32,
    pub creation_date: DateTime,
    pub file_path: String,
    pub line_number: String,
    pub function_name: String,
    pub request: String,
    pub error_type: String,
    pub error_details: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    CreationDate,
    FilePath,
    LineNumber,
    FunctionName,
    Request,
    ErrorType,
    ErrorDetails,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::CreationDate => ColumnType::DateTime.def(),
            Self::FilePath => ColumnType::String(StringLen::None).def(),
            Self::LineNumber => ColumnType::String(StringLen::None).def(),
            Self::FunctionName => ColumnType::String(StringLen::None).def(),
            Self::Request => ColumnType::String(StringLen::None).def(),
            Self::ErrorType => ColumnType::String(StringLen::None).def(),
            Self::ErrorDetails => ColumnType::String(StringLen::None).def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
