//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "indicators"
    }
}

#[derive(
    Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize, Default,
)]
pub struct Model {
    pub id: i32,
    pub strategy_id: i32,
    pub is_active: bool,
    pub symbol: String,
    pub nick: String,
    pub direction: String,
    pub is_percentage: bool,
    pub value: Decimal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    StrategyId,
    IsActive,
    Symbol,
    Nick,
    Direction,
    IsPercentage,
    Value,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Strategies,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::StrategyId => ColumnType::Integer.def(),
            Self::IsActive => ColumnType::Boolean.def(),
            Self::Symbol => ColumnType::String(StringLen::None).def(),
            Self::Nick => ColumnType::String(StringLen::None).def(),
            Self::Direction => ColumnType::String(StringLen::None).def(),
            Self::IsPercentage => ColumnType::Boolean.def(),
            Self::Value => ColumnType::Decimal(Some((18u32, 8u32))).def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Strategies => Entity::belongs_to(super::strategies::Entity)
                .from(Column::StrategyId)
                .to(super::strategies::Column::Id)
                .into(),
        }
    }
}

impl Related<super::strategies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Strategies.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
