//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "integration_log"
    }
}

#[derive(
    Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize, Default,
)]
pub struct Model {
    pub id: i32,
    pub creation_date: DateTime,
    pub integration_name: String,
    pub function_name: String,
    pub url: String,
    pub request: String,
    pub response: String,
    pub status_code: i32,
    pub error_message: String,
    pub execution_time_ms: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    CreationDate,
    IntegrationName,
    FunctionName,
    Url,
    Request,
    Response,
    StatusCode,
    ErrorMessage,
    ExecutionTimeMs,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::CreationDate => ColumnType::DateTime.def(),
            Self::IntegrationName => ColumnType::String(StringLen::None).def(),
            Self::FunctionName => ColumnType::String(StringLen::None).def(),
            Self::Url => ColumnType::String(StringLen::None).def(),
            Self::Request => ColumnType::String(StringLen::None).def(),
            Self::Response => ColumnType::String(StringLen::None).def(),
            Self::StatusCode => ColumnType::Integer.def(),
            Self::ErrorMessage => ColumnType::String(StringLen::None).def(),
            Self::ExecutionTimeMs => ColumnType::Integer.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
