//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "ledgers"
    }
}

#[derive(
    Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize, Default,
)]
pub struct Model {
    pub id: i32,
    pub order_id: Option<i32>,
    pub record_type_id: i32,
    pub creation_date: DateTime,
    pub asset_id: i32,
    pub free_amount: Decimal,
    pub free_previous_balance: Decimal,
    pub free_new_balance: Decimal,
    pub locked_amount: Decimal,
    pub locked_previous_balance: Decimal,
    pub locked_new_balance: Decimal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    OrderId,
    RecordTypeId,
    CreationDate,
    AssetId,
    FreeAmount,
    FreePreviousBalance,
    FreeNewBalance,
    LockedAmount,
    LockedPreviousBalance,
    LockedNewBalance,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Assets,
    RecordTypes,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::OrderId => ColumnType::Integer.def().null(),
            Self::RecordTypeId => ColumnType::Integer.def(),
            Self::CreationDate => ColumnType::DateTime.def(),
            Self::AssetId => ColumnType::Integer.def(),
            Self::FreeAmount => ColumnType::Decimal(Some((18u32, 8u32))).def(),
            Self::FreePreviousBalance => ColumnType::Decimal(Some((18u32, 8u32))).def(),
            Self::FreeNewBalance => ColumnType::Decimal(Some((18u32, 8u32))).def(),
            Self::LockedAmount => ColumnType::Decimal(Some((18u32, 8u32))).def(),
            Self::LockedPreviousBalance => ColumnType::Decimal(Some((18u32, 8u32))).def(),
            Self::LockedNewBalance => ColumnType::Decimal(Some((18u32, 8u32))).def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Assets => Entity::belongs_to(super::assets::Entity)
                .from(Column::AssetId)
                .to(super::assets::Column::Id)
                .into(),
            Self::RecordTypes => Entity::belongs_to(super::record_types::Entity)
                .from(Column::RecordTypeId)
                .to(super::record_types::Column::Id)
                .into(),
        }
    }
}

impl Related<super::assets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Assets.def()
    }
}

impl Related<super::record_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecordTypes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
