//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "ledgers"
    }
}

#[derive(
    Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize, Default,
)]
pub struct Model {
    pub id: i32,
    pub order_id: Option<i32>,
    pub record_type_id: i32,
    pub creation_date: DateTime,
    pub base_asset_id: i32,
    pub base_asset_amount: Decimal,
    pub base_asset_previous_balance: Decimal,
    pub base_asset_new_balance: Decimal,
    pub quote_asset_id: i32,
    pub quote_asset_amount: Decimal,
    pub quote_asset_previous_balance: Decimal,
    pub quote_asset_new_balance: Decimal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    OrderId,
    RecordTypeId,
    CreationDate,
    BaseAssetId,
    BaseAssetAmount,
    BaseAssetPreviousBalance,
    BaseAssetNewBalance,
    QuoteAssetId,
    QuoteAssetAmount,
    QuoteAssetPreviousBalance,
    QuoteAssetNewBalance,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Assets2,
    Assets1,
    RecordTypes,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::OrderId => ColumnType::Integer.def().null(),
            Self::RecordTypeId => ColumnType::Integer.def(),
            Self::CreationDate => ColumnType::DateTime.def(),
            Self::BaseAssetId => ColumnType::Integer.def(),
            Self::BaseAssetAmount => ColumnType::Decimal(Some((18u32, 8u32))).def(),
            Self::BaseAssetPreviousBalance => ColumnType::Decimal(Some((18u32, 8u32))).def(),
            Self::BaseAssetNewBalance => ColumnType::Decimal(Some((18u32, 8u32))).def(),
            Self::QuoteAssetId => ColumnType::Integer.def(),
            Self::QuoteAssetAmount => ColumnType::Decimal(Some((18u32, 8u32))).def(),
            Self::QuoteAssetPreviousBalance => ColumnType::Decimal(Some((18u32, 8u32))).def(),
            Self::QuoteAssetNewBalance => ColumnType::Decimal(Some((18u32, 8u32))).def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Assets2 => Entity::belongs_to(super::assets::Entity)
                .from(Column::BaseAssetId)
                .to(super::assets::Column::Id)
                .into(),
            Self::Assets1 => Entity::belongs_to(super::assets::Entity)
                .from(Column::QuoteAssetId)
                .to(super::assets::Column::Id)
                .into(),
            Self::RecordTypes => Entity::belongs_to(super::record_types::Entity)
                .from(Column::RecordTypeId)
                .to(super::record_types::Column::Id)
                .into(),
        }
    }
}

impl Related<super::record_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecordTypes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
