//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "pairs"
    }
}

#[derive(
    Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize, Default,
)]
pub struct Model {
    pub id: i32,
    pub base_asset_id: i32,
    pub quote_asset_id: i32,
    pub symbol: String,
    pub update_date: DateTime,
    pub all_time_high_price: Decimal,
    pub all_time_high_date: DateTime,
    pub percent_from_all_time_high: Decimal,
    pub fifteen_minutes_price_percent_change: Decimal,
    pub thirty_minutes_price_percent_change: Decimal,
    pub hour_price_percent_change: Decimal,
    pub six_hours_price_percent_change: Decimal,
    pub twelve_hours_price_percent_change: Decimal,
    pub day_price_percent_change: Decimal,
    pub week_price_percent_change: Decimal,
    pub month_price_percent_change: Decimal,
    pub year_price_percent_change: Decimal,
    pub price_filter_min_price: Decimal,
    pub price_filter_max_price: Decimal,
    pub price_filter_tick_size: Decimal,
    pub lot_size_min_qty: Decimal,
    pub lot_size_max_qty: Decimal,
    pub lot_size_step_size: Decimal,
    pub iceberg_parts_limit: i32,
    pub market_lot_size_min_qty: Decimal,
    pub market_lot_size_max_qty: Decimal,
    pub market_lot_size_step_size: Decimal,
    pub trailing_delta_min_trailing_above_delta: i32,
    pub trailing_delta_max_trailing_above_delta: i32,
    pub trailing_delta_min_trailing_below_delta: i32,
    pub trailing_delta_max_trailing_below_delta: i32,
    pub percent_price_by_side_bid_multiplier_up: Decimal,
    pub percent_price_by_side_bid_multiplier_down: Decimal,
    pub percent_price_by_side_ask_multiplier_up: Decimal,
    pub percent_price_by_side_ask_multiplier_down: Decimal,
    pub percent_price_by_side_avg_price_mins: i32,
    pub notional_min_notional: Decimal,
    pub notional_apply_min_to_market: bool,
    pub notional_max_notional: Decimal,
    pub notional_apply_max_to_market: bool,
    pub notional_avg_price_mins: i32,
    pub max_num_orders: i32,
    pub max_num_algo_orders: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    BaseAssetId,
    QuoteAssetId,
    Symbol,
    UpdateDate,
    AllTimeHighPrice,
    AllTimeHighDate,
    PercentFromAllTimeHigh,
    FifteenMinutesPricePercentChange,
    ThirtyMinutesPricePercentChange,
    HourPricePercentChange,
    SixHoursPricePercentChange,
    TwelveHoursPricePercentChange,
    DayPricePercentChange,
    WeekPricePercentChange,
    MonthPricePercentChange,
    YearPricePercentChange,
    PriceFilterMinPrice,
    PriceFilterMaxPrice,
    PriceFilterTickSize,
    LotSizeMinQty,
    LotSizeMaxQty,
    LotSizeStepSize,
    IcebergPartsLimit,
    MarketLotSizeMinQty,
    MarketLotSizeMaxQty,
    MarketLotSizeStepSize,
    TrailingDeltaMinTrailingAboveDelta,
    TrailingDeltaMaxTrailingAboveDelta,
    TrailingDeltaMinTrailingBelowDelta,
    TrailingDeltaMaxTrailingBelowDelta,
    PercentPriceBySideBidMultiplierUp,
    PercentPriceBySideBidMultiplierDown,
    PercentPriceBySideAskMultiplierUp,
    PercentPriceBySideAskMultiplierDown,
    PercentPriceBySideAvgPriceMins,
    NotionalMinNotional,
    NotionalApplyMinToMarket,
    NotionalMaxNotional,
    NotionalApplyMaxToMarket,
    NotionalAvgPriceMins,
    MaxNumOrders,
    MaxNumAlgoOrders,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Actions,
    Assets2,
    Assets1,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::BaseAssetId => ColumnType::Integer.def(),
            Self::QuoteAssetId => ColumnType::Integer.def(),
            Self::Symbol => ColumnType::Text.def(),
            Self::UpdateDate => ColumnType::DateTime.def(),
            Self::AllTimeHighPrice => ColumnType::Decimal(None).def(),
            Self::AllTimeHighDate => ColumnType::DateTime.def(),
            Self::PercentFromAllTimeHigh => ColumnType::Decimal(None).def(),
            Self::FifteenMinutesPricePercentChange => ColumnType::Decimal(None).def(),
            Self::ThirtyMinutesPricePercentChange => ColumnType::Decimal(None).def(),
            Self::HourPricePercentChange => ColumnType::Decimal(None).def(),
            Self::SixHoursPricePercentChange => ColumnType::Decimal(None).def(),
            Self::TwelveHoursPricePercentChange => ColumnType::Decimal(None).def(),
            Self::DayPricePercentChange => ColumnType::Decimal(None).def(),
            Self::WeekPricePercentChange => ColumnType::Decimal(None).def(),
            Self::MonthPricePercentChange => ColumnType::Decimal(None).def(),
            Self::YearPricePercentChange => ColumnType::Decimal(None).def(),
            Self::PriceFilterMinPrice => ColumnType::Decimal(None).def(),
            Self::PriceFilterMaxPrice => ColumnType::Decimal(None).def(),
            Self::PriceFilterTickSize => ColumnType::Decimal(None).def(),
            Self::LotSizeMinQty => ColumnType::Decimal(None).def(),
            Self::LotSizeMaxQty => ColumnType::Decimal(None).def(),
            Self::LotSizeStepSize => ColumnType::Decimal(None).def(),
            Self::IcebergPartsLimit => ColumnType::Integer.def(),
            Self::MarketLotSizeMinQty => ColumnType::Decimal(None).def(),
            Self::MarketLotSizeMaxQty => ColumnType::Decimal(None).def(),
            Self::MarketLotSizeStepSize => ColumnType::Decimal(None).def(),
            Self::TrailingDeltaMinTrailingAboveDelta => ColumnType::Integer.def(),
            Self::TrailingDeltaMaxTrailingAboveDelta => ColumnType::Integer.def(),
            Self::TrailingDeltaMinTrailingBelowDelta => ColumnType::Integer.def(),
            Self::TrailingDeltaMaxTrailingBelowDelta => ColumnType::Integer.def(),
            Self::PercentPriceBySideBidMultiplierUp => ColumnType::Decimal(None).def(),
            Self::PercentPriceBySideBidMultiplierDown => ColumnType::Decimal(None).def(),
            Self::PercentPriceBySideAskMultiplierUp => ColumnType::Decimal(None).def(),
            Self::PercentPriceBySideAskMultiplierDown => ColumnType::Decimal(None).def(),
            Self::PercentPriceBySideAvgPriceMins => ColumnType::Integer.def(),
            Self::NotionalMinNotional => ColumnType::Decimal(None).def(),
            Self::NotionalApplyMinToMarket => ColumnType::Boolean.def(),
            Self::NotionalMaxNotional => ColumnType::Decimal(None).def(),
            Self::NotionalApplyMaxToMarket => ColumnType::Boolean.def(),
            Self::NotionalAvgPriceMins => ColumnType::Integer.def(),
            Self::MaxNumOrders => ColumnType::Integer.def(),
            Self::MaxNumAlgoOrders => ColumnType::Integer.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Actions => Entity::has_many(super::actions::Entity).into(),
            Self::Assets2 => Entity::belongs_to(super::assets::Entity)
                .from(Column::BaseAssetId)
                .to(super::assets::Column::Id)
                .into(),
            Self::Assets1 => Entity::belongs_to(super::assets::Entity)
                .from(Column::QuoteAssetId)
                .to(super::assets::Column::Id)
                .into(),
        }
    }
}

impl Related<super::actions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Actions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
