//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "strategies"
    }
}

#[derive(
    Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize, Default,
)]
pub struct Model {
    pub id: i32,
    pub name: String,
    pub is_active: bool,
    pub can_trade: bool,
    pub stream_name: String,
    pub description: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Name,
    IsActive,
    CanTrade,
    StreamName,
    Description,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Orders,
    StrategiesPairAssets,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::Name => ColumnType::String(StringLen::None).def(),
            Self::IsActive => ColumnType::Boolean.def(),
            Self::CanTrade => ColumnType::Boolean.def(),
            Self::StreamName => ColumnType::String(StringLen::None).def(),
            Self::Description => ColumnType::String(StringLen::None).def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Orders => Entity::has_many(super::orders::Entity).into(),
            Self::StrategiesPairAssets => {
                Entity::has_many(super::strategies_pair_assets::Entity).into()
            }
        }
    }
}

impl Related<super::orders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Orders.def()
    }
}

impl Related<super::strategies_pair_assets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StrategiesPairAssets.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
