[package]
name = "models"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "models"
path = "src/lib.rs"

[dependencies]
chrono = { workspace = true }
sea-orm = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
once_cell = { workspace = true }
